### ISSUE TITLE
Check and update Postman screenshots to reflect HTTPS vs. HTTP

### ISSUE THREAD

**Issue by dstaudt** [CiscoDevNet/labs-xapi#13]
collab-xapi-intro

**Comment by dstaudt** [comment]
also needed in collab-xapi-branding

**Comment by ObjectIsAdvantag** [comment]
Good point, let's turn all samples to HTTPS.

Let's check if HTTPS is activated by default for on-premises and Spark-registered devices.

**Comment by ObjectIsAdvantag** [comment]
Looks good for Spark-registered,
![image](https://user-images.githubusercontent.com/49432/39517915-9f90bcb6-4e01-11e8-9270-8f4b4a89ce68.png)

**Comment by ObjectIsAdvantag** [comment]
@dstaudt can you check for on-premises, and not registered devices such as our Sandbox Room Kits.

**Comment by dstaudt** [comment]
Confirm HTTP+HTTPS enabled by default for the premise/sandbox devices

**Comment by ObjectIsAdvantag** [comment]
Both HTTPS and HTTP are also enabled on the Sandbox.
I checked: most snapshots have been updated to reflect HTTPS by default.
Closing
