### ISSUE TITLE
Reference the RoomKit Sandbox

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [CiscoDevNet/labs-xapi#17]
Added to the In-Room Controls lab.

TODO: add to the Intro lab mainly as it does not make a lot of sense for branding

**Comment by dstaudt** [comment]
I found the Sandbox useful when working on the Branding lab as well.  I used the 'screenshot' facility in the web UI to confirm status and changes on the Touch10, though couldn't confirm main screen configs.

I would vote for inclusion in all 3 labs for consistency and for keeping barrier-to-entry low...

**Comment by ObjectIsAdvantag** [comment]
The Sandbox is mentionned in the intro lab.
Still need to add a mention in the pre-req and BYOD of other labs

**Comment by ObjectIsAdvantag** [comment]
added via the anchor
https://github.com/CiscoDevNet/awesome-xapi#sandboxes
