### ISSUE TITLE
Feedback from Steve Hill

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#18]
Mostly note the same issues I raised about cut and paste on 3rd lab (which probably needs an enhancement) as well as time adjustment. 

![image](https://user-images.githubusercontent.com/18483964/39541488-e146fabe-4e13-11e8-8b90-e2e36dd4f84d.png)

**Comment by ObjectIsAdvantag** [comment]
Thanks for the feedback.

I believe the code instructions for custom In-Room Controls have been updated for SEVT.

The timing mainly covers the hands-on part. Reading thru referenced docs, discovering the Web UI, tools is not part of it. 

Closing, let me know if I missed something
