### ISSUE TITLE
Feedback from Craig Tait

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#19]
![image](https://user-images.githubusercontent.com/18483964/39587004-85ddd568-4ec6-11e8-8763-e1c66de56ea4.png)
Hey Steve Greenberg - results of my run-through:
Intro to xapi Lab - 60 minutes (included installing node and Postman)
Some minor documentation changes…
Page 2, Step 6:
“…new window will appear on the left” (should be “right”)
Step 5:
On a DX, there is no ‘xcommand Standby Deactivate’
xconfiguration Standby
*c xConfiguration Standby Control: On
*c xConfiguration Standby Delay: 10
*c xConfiguration Standby WakeupOnMotionDetection: Off
** end
Step 6:
“For this lab, we have pre-generated… based on the ‘integration:integrator’ username and password” (should read “integrator:integrator”)
Because in Step 2:, we said,
“Enter ‘integrator’ as Username”
Step 8:
cURL is missing the —insecure option, because we’re going against a self-signed cert.
curl -X POST https://192.168.1.34/putxml
-H 'Authorization: Basic aW50ZWdyYXRvcjppbnRlZ3JhdG9y'
-H 'Content-Type: text/xml'
-d '<Command><Dial><Number>roomkit@sparkdemos.com</Number></Dial></Command>'
curl: (60) SSL certificate problem: self signed certificate
add —insecure to the cURL command and it works
Branding Lab - 30 minutes
In-Room Controls - 40 minutes

**Comment by dstaudt** [comment]
Thanks Steve/Craig - all issues updated, except the first one, which I could not find (on Page 2, or elsewhere:)

Page 2, Step 6:
“…new window will appear on the left” (should be “right”)
