### ISSUE TITLE
collab-xapi-intro modifications

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#4]
Step 3: Add a note "Access to Advanced Settings requires that you are connected to the same network as the room device."

Step 4:  "and sign out if you're already signed in...." by clicking on the username in the top right. 

Step 7: Standby status from standby.js returned [object Object] instead of correct status. 

Step 8: CURL command assumes OSX/Linux as \ does not let you continue on next line in Windows.

**Comment by ObjectIsAdvantag** [comment]
Integrated comments, added snapshot for failing "Access to advanced settings", and fixed code to fetch StandBy status.

THANKS @stgreenb for these comments.
