### ISSUE TITLE
collab-xapi-branding

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/labs-xapi#5]
Step 4: see error "invalid type" when running branding upload from postman. 
![image](https://user-images.githubusercontent.com/18483964/38209075-21efe396-3681-11e8-9f11-1780ca6b6919.png)

Step 5: See error when attempting to run customMessage.js
![image](https://user-images.githubusercontent.com/18483964/38209010-e1369a16-3680-11e8-83ad-97d7ebfba45a.png)

**Comment by bjornars** [comment]
For the first one, try dropping the spaces inside the `Type` tag.
For the second, try `npm install` to install the required dependencies - I'm not sure how the docs read on this one, but that would be my guess.

**Comment by stgreenb** [comment]
@bjornars Indeed the spaces fixed the issue. The sample should be updated as it had the spaces. 
I did miss the npm install on the 2nd problem. however I get a different error. 
![image](https://user-images.githubusercontent.com/18483964/38216993-944ae800-369a-11e8-8338-48005d720c54.png)

**Comment by stgreenb** [comment]
Now updated node to a more current version on that machine and it worked.

**Comment by ObjectIsAdvantag** [comment]
I fixed the lab for step 4 (space), and step 5 (changed to console.log to avoid errors with older versions of node, let's stick to console.log & console.error standard functions)

THANKS @stgreenb & @bjornars for the feedback/diagnose.
